### ISSUE TITLE
Add an English guide: Deploy TiDB Operator and a TiDB Cluster on KubeSphere 

### ISSUE THREAD

**Issue by Sherlock113** [kubesphere/website#1049]
@Felixnoo When you are available, please add a guide in External Applications in the chapter App Store. You can refer to these two blogs:

https://kubesphere.io/blogs/tidb-on-kubesphere-using-qke/
https://pingcap.com/blog/run-cloud-native-distributed-database-on-hybrid-cloud-kubernetes-platform

Note that do not use the account `admin` directly. Make sure you use the correct account. You can refer to [Application Lifecycle Management](https://kubesphere.io/docs/application-store/app-lifecycle-management/) and [Create Workspaces, Projects, Accounts and Roles](https://kubesphere.io/docs/quick-start/create-workspace-and-project/).

**Comment by Felixnoo** [comment]
Doc added.
