### ISSUE TITLE
Broken links on KubeSphere Console

### ISSUE THREAD

**Issue by FeynmanZhou** [kubesphere/website#1122]
These two dead links are raised by users, please scan the KubeSphere console for the whole check.

- [ ] Platform settings: https://v3-0.docs.kubesphere.io/docs/cluster-administration/platform-settings/customize-basic-information/
![image](https://user-images.githubusercontent.com/40452856/109178177-8d6d2300-77c3-11eb-834e-ba190298b79a.png)

- [ ] Grayscale release: https://v3-0.docs.kubesphere.io/docs/project-user-guide/grayscale/overview/
![image](https://user-images.githubusercontent.com/40452856/109178287-aa095b00-77c3-11eb-8ac8-371b707ab881.png)

**Comment by Sherlock113** [comment]
If you do change links in Documentation, I think there are at least three issues you need to consider.

1. The URL on the KubeSphere console actually goes against the standard naming convention of our documentation. For example, the correct URL of our grayscale release page is https://v3-0.docs.kubesphere.io/docs/project-user-guide/grayscale-release/overview/, which matches our doc's structure:

![image](https://user-images.githubusercontent.com/65327072/109261825-70743680-783b-11eb-9f9f-122782931ddf.png)

Obvious, `grayscale-release` is more reasonable here than `grayscale`.

2. For the link Platform Settings (https://v3-0.docs.kubesphere.io/docs/cluster-administration/platform-settings/customize-basic-information/), the correct link is https://v3-0.docs.kubesphere.io/docs/cluster-administration/platform-settings/. As you can see below, `Platform Settings` itself is an individual file.

![image](https://user-images.githubusercontent.com/65327072/109262105-eaa4bb00-783b-11eb-93c7-e08d9ab56410.png)

If you want to change the doc's URL to match the link in the console, you have to create a folder called `Platform Settings`, which only contains a single guide `customized-basic-information.md`. This is really unnecessary and unprofessional for documentation, unless you deliberately add more guides in this folder. Well, if you do this, we need to consider what can be included in this folder....

3. Once the folder name is changed, all links, regardless of relative or absolute ones, that direct to guides in the folder will be dead links, causing more problems. Usually, we do not refactor a chapter or sub-chapter unless the guides within them are really problematic.

**Comment by Sherlock113** [comment]
I know dead links in the console can be misleading to our users. To solve this issue, there are three possible ways:

1. Change and refactor links in the documentation, which is not reasonable to me as I said above.
2. Change the URL in the console directly, which I am not sure if it is possible as KubeSphere 3.0 is already published.
3. Leave these links as they are and fix them in 3.1, which will be released before long.

**Comment by Sherlock113** [comment]
Fixed in https://github.com/kubesphere/website/pull/1409
Need verification.

**Comment by FeynmanZhou** [comment]
Verified, thanks!
