### ISSUE TITLE
Is it possible to generate index page for each chapter automatically

### ISSUE THREAD

**Issue by FeynmanZhou** [kubesphere/website#1128]
Currently, all contents in the index pages are manually maintained by developers, and it will cause the search result not expected as users' need, see this [issue](https://github.com/kubesphere/docs.kubesphere.io/issues/768) for details.

**Comment by Sherlock113** [comment]
I think the very core issue is that whether the description of each title can be generated on the index page....

**Comment by liuboaibc** [comment]
Can be generated automatically，i wil upgrade it.

**Comment by FeynmanZhou** [comment]
> Can be generated automatically，i wil upgrade it.

Sounds good!

**Comment by liuboaibc** [comment]
Some pages have too few descriptions and need to be improved.
