### ISSUE TITLE
Add FAQ documents for KubeSphere DevOps 

### ISSUE THREAD

**Issue by FeynmanZhou** [kubesphere/website#1184]
KubeSphere DevOps system is the most common-used feature in the community. There is a lot of DevOps questions and answers on the Chinese forum and Github issue, but there are not documents of KubeSphere DevOps in the [FAQ section](https://kubesphere.com.cn/en/docs/faq/). Please help to conclude those frequently-asked questions for the KubeSphere DevOps system.

**Comment by Felixnoo** [comment]
Will work on it.
