### ISSUE TITLE
安装后验证总是提示ContainerCreating

### ISSUE THREAD

**Issue by tomcyndi** [kubesphere/website#1198]
安装完k8s和Kubersphere后，执行命令kubectl logs -n kubesphere-system $(kubectl get pod -n kubesphere-system -l app=ks-install -o jsonpath='{.items[0].metadata.name}') -f

结果提示：
Error from server (BadRequest): container "installer" in pod "ks-installer-7cb866bd-f9jt4" is waiting to start: ContainerCreating

**Comment by FeynmanZhou** [comment]
Could you inspect the Pod status and verify if there is any abnormal Pods?

```
$ kubectl get pod --all-namespaces
```

English only in Github, you may need to reopen a new issue in English, or raise a Chinese issue via [Chinese Forum](https://kubesphere.com.cn/forum/).
