### ISSUE TITLE
Pipeline Settings doc is missing

### ISSUE THREAD

**Issue by FeynmanZhou** [kubesphere/website#1254]
The [Pipeline Settings](https://kubesphere.io/docs/devops-user-guide/how-to-use/pipeline-settings/) doc is missing in v3.0, please help to complete this doc refer to the [documentation of KubeSphere v2.1](https://v2-1.docs.kubesphere.io/docs/zh-CN/system-settings/edit-system-settings/).

**Comment by Felixnoo** [comment]
I can't find the contents related to pipeline settings from v2.1 documentation. Am I missing something here?

**Comment by Felixnoo** [comment]
Document added in [this PR](https://github.com/kubesphere/website/pull/1332). Please also take a look at it if you are available. Thanks.

**Comment by Felixnoo** [comment]
[Document in v3.0](https://github.com/kubesphere/website/pull/1335) added, too. I guess we can close this issue.
