### ISSUE TITLE
Add Navigations on the top of the Chinese Forum

### ISSUE THREAD

**Issue by FeynmanZhou** [kubesphere/website#1320]
Add these buttons on the top of the Chinese forum:

- 中文官网
- GitHub
- 官方文档
- [服务与支持](https://kubesphere.cloud/)

Example: https://bbs.halo.run/

**Comment by liuboaibc** [comment]
done @FeynmanZhou

**Comment by FeynmanZhou** [comment]
> done @FeynmanZhou

It looks like the layout is incorrect. 

![image](https://user-images.githubusercontent.com/40452856/113407163-5c45cb00-93df-11eb-9976-ed59c11f6633.png)
