### ISSUE TITLE
Change font of code blocks to monospace font

### ISSUE THREAD

**Issue by JohnNiang** [kubesphere/website#1359]
Change font of code blocks to monospace font

- Current

![image](https://user-images.githubusercontent.com/16865714/114809486-db260500-9ddc-11eb-8534-529d4c4af333.png)

- Expected

![image](https://user-images.githubusercontent.com/16865714/114809606-11638480-9ddd-11eb-9be9-1053163f3708.png)

**Comment by Sherlock113** [comment]
@JohnNiang Just to confirm, what OS are you using? It seems Windows will have that font and it looks fine on Mac.

**Comment by JohnNiang** [comment]
@Sherlock113 Linux qingcloud 5.10.26-1-MANJARO #1 SMP PREEMPT Thu Mar 25 16:56:17 UTC 2021 x86_64 GNU/Linux

**Comment by JohnNiang** [comment]
Fixed by #1362 

![image](https://user-images.githubusercontent.com/16865714/115177198-4d5e5880-a101-11eb-9052-d0c5f2360d9e.png)
