### ISSUE TITLE
404 page in v3.0

### ISSUE THREAD

**Issue by FeynmanZhou** [kubesphere/website#1397]
404 page in v3.0 (Online version):
https://v3-0.docs.kubesphere.io/docs/cluster-administration/platform-settings/customize-basic-information/

![image](https://user-images.githubusercontent.com/40452856/115487798-018bea80-a28c-11eb-9951-51a7b941750d.png)

But it works in v3.1:
https://v3-1.docs.kubesphere.io/docs/cluster-administration/platform-settings/customize-basic-information/

It needs to be fixed in v3.0.

**Comment by FeynmanZhou** [comment]
cc @kubesphere/sig-docs

**Comment by Sherlock113** [comment]
See this PR: https://github.com/kubesphere/website/issues/1122

**Comment by Sherlock113** [comment]
Fixed in https://github.com/kubesphere/website/pull/1405
