### ISSUE TITLE
[Have video] Add a tutorial to introduce how to use Jenkins sharedlibrary in KuebSphere Devops

### ISSUE THREAD

**Issue by LinuxSuRen** [kubesphere/website#1430]
Many users choose to adopt [shared-library](https://www.jenkins.io/doc/book/pipeline/shared-libraries/) to improve their Pipeline practice. But some KubeSphere users might curious about can I use it in KubeSphere DevOps? The answer is definitely yes! But how?

So, in my opinion, providing a tutorial is meaningful. If anyone wants to help to write it, I've [some videos (in Chinese)](https://www.bilibili.com/video/BV1fp4y1r7Dd?p=20) about the shared library. Hopefully, those videos can give you some hints.

/area devops
/priority medium

**Comment by Felixnoo** [comment]
On it.

**Comment by LinuxSuRen** [comment]
You can find the video from [here](https://www.bilibili.com/video/BV1yy4y137eC).
