### ISSUE TITLE
Add a tutorial to introduce how to trigger Pipeline via webhook

### ISSUE THREAD

**Issue by LinuxSuRen** [kubesphere/website#1477]
/area devops
/priority medium

The following screenshot might be helpful to you:

![image](https://user-images.githubusercontent.com/1450685/116655228-4ff06600-a9bd-11eb-8742-aeb37d2a1550.png)

**Comment by Felixnoo** [comment]
On it.

**Comment by LinuxSuRen** [comment]
There're serval ways to use webhook with Pipeline:

* [ ] Multi-branch webhook
* [ ] SCM webhook
* [ ] Generic webhook

**Comment by Felixnoo** [comment]
> There're serval ways to use webhook with Pipeline:
> 
> * [ ]  Multi-branch webhook
> * [ ]  SCM webhook
> * [ ]  Generic webhook

I thought users just need to put the **Webhook Push** shown in the screenshot to the GitHub repository Settings to use webhook with KS pipelines. 

As for Generic webhook, SCM webhook, and Multi-branch webhook, do you mean we have three different ways to make configurations in KS pipelines to use these different kinds of webhooks?

I did some research on webhook. Is it correct to say that Generic webhook uses Payload URL ending with `/generic-webhook-trigger/invoke` and SCM webhook uses Payload URL ending with `/github-webhook/`? And for Multi-branch webhook, I guess the **Webhook Push** provided by KS pipeline is able to trigger pipeline per changes in specific branches?

Help needed...

**Comment by LinuxSuRen** [comment]
I'll show them in the next [DevOps SIG](https://github.com/kubesphere/community/tree/master/sig-devops) meeting.
