### ISSUE TITLE
The URL for "Add edge nodes to a cluster" is 404. Please fix it

### ISSUE THREAD

**Issue by yinmin2020** [kubesphere/website#1479]
![image](https://user-images.githubusercontent.com/65068467/116665721-add87a00-a9cc-11eb-858a-142779fcc2dd.png)
![image](https://user-images.githubusercontent.com/65068467/116665745-b3ce5b00-a9cc-11eb-9c42-cdb26c42dbfe.png)
https://kubesphere.io/zh/docs/installing-on-linux/cluster-operation/add-edge-nodes/

**Comment by Sherlock113** [comment]
Thank you. The issue was solved.
