### ISSUE TITLE
[Have video] Add a tutorial about how to config Jenkins via CasC

### ISSUE THREAD

**Issue by LinuxSuRen** [kubesphere/website#1483]
See also https://github.com/jenkinsci/configuration-as-code-plugin

/area devops
/priority medium
/help

**Comment by Felixnoo** [comment]
On it.

**Comment by Felixnoo** [comment]
@LinuxSuRen Hi, I'm having difficulty understanding what is the concept of this tutorial. Is it for users who want to configure Jenkins via CasC after KS is installed, or for users who have used KS for a while and want to reproduce the configuration of KS Jenkins on another Jenkins instance? 
I guess I need your help in setting up a framework for this tutorial.

**Comment by LinuxSuRen** [comment]
For those who want to make some changes to the Jenkins configuration, they need to do it by the CasC way.

I think this [video](https://www.bilibili.com/video/BV1mE411i7BV) might be able to give you some background about [CasC](https://github.com/jenkinsci/configuration-as-code-plugin). I can show you how to do it with KubeSphere in the next DevOps SIG meeting.
