### ISSUE TITLE
如何自己制作一个 podTemplate 用于 dotnet 5.0 的构建和 docker 镜像构建

### ISSUE THREAD

**Issue by freemanke** [kubesphere/website#1486]
官方提供了几个标准的 nodejs go 的 agent ，我如何自己制作一个用于 dotnet 5.0 的 agent

**Comment by FeynmanZhou** [comment]
Take a look at [this guide](https://v2-1.docs.kubesphere.io/docs/zh-CN/devops/jenkins-agent/), let us know if this guide is helpful.

**Comment by freemanke** [comment]
Jenkinsfile like below, always get error as snapshot, please help to fix out what's wrong!
![image](https://user-images.githubusercontent.com/1439128/116845977-e6b95e80-ac19-11eb-84c4-7e1a88f542cc.png)
[Jenkinsfile.txt](https://github.com/kubesphere/website/files/6413051/Jenkinsfile.txt)

**Comment by shanghai636848** [comment]
帮忙给提供一个完整的demo吗？
