### ISSUE TITLE
3.1文档链接丢失

### ISSUE THREAD

**Issue by clh-cod** [kubesphere/website#1506]
从3.0的文档处[https://v3-0.docs.kubesphere.io/zh/docs/]，没有3.1的文档地址链接
![image](https://user-images.githubusercontent.com/69289383/117521656-880d2f80-afe1-11eb-98bc-f5115935e37b.png)

**Comment by FeynmanZhou** [comment]
Thanks for your feedback. It should be added in the list.

BTW, we also need to add a statement for the older version, as Kubernetes has the same maintaining lifecycle for the older versions of the documentation. 

![image](https://user-images.githubusercontent.com/40452856/117521909-e555b080-afe2-11eb-979f-c327f7726aae.png)

**Comment by FeynmanZhou** [comment]
@clh-cod Fiexed. https://v3-0.docs.kubesphere.io/zh/docs/

**Comment by clh-cod** [comment]
@FeynmanZhou thanks.
