### ISSUE TITLE
Add KubeSphere official support list into FAQ

### ISSUE THREAD

**Issue by zheng1** [kubesphere/website#1553]
Add a page to organize KubeSphere official support list in a unified way.

It can be divided into the following major sections, with the following sources for reference

Section | Refer from
------------ | -------------
OS and Kernel Versions List | https://kubesphere.io/docs/installing-on-linux/introduction/multioverview/#system-requirements
Version list for Kubernetes |  https://github.com/kubesphere/kubekey/blob/master/docs/kubernetes-versions.md 
List of container such as Docker versions | @pixiake 
CNI Plugin List | @pixiake 
CSI Plugin List | @pixiake 
Browser List | https://kubesphere.com.cn/docs/faq/console/console-web-browser/

/cc @kubesphere/sig-docs 
/area docs

**Comment by pixiake** [comment]
container-engine: 
Docker  19.3.8+

cni-plugins: 
calico / flannel 

csi-plugins: 
neonsan-csi / qingcloud-csi / ceph-csi / nfs-client-provisioner

**Comment by Sherlock113** [comment]
@zheng1 Hi, I want to double check with you. The original Chinese text is "容器如 Docker 在 KubeSphere 官方支持的版本列表中". I am wondering whether it is more accurate to say "容器运行时" instead of "容器" as KubeSphere supports different container runtimes.

**Comment by zheng1** [comment]
@Sherlock113 Yes, you are right. 'Container runtime' is more exact.
https://kubernetes.io/docs/setup/production-environment/container-runtimes/

**Comment by Sherlock113** [comment]
> @Sherlock113 Yes, you are right. 'Container runtime' is more exact.
> https://kubernetes.io/docs/setup/production-environment/container-runtimes/

OK. Working on it.
