### ISSUE TITLE
[Have video] Add a tutorial about how to use the private Nexus in KubeSphere Devops

### ISSUE THREAD

**Issue by LinuxSuRen** [kubesphere/website#1567]
If you want to help us to contribute this document. You can check out [the official KubeSphere DevOps document](https://kubesphere.com.cn/docs/devops-user-guide/). Please see also the [video](https://www.bilibili.com/video/BV1fp4y1r7Dd?p=28) if you don't know about the private Nexus use cases.

/help
/priority medium
/area devops

**Comment by Felixnoo** [comment]
I'll take a look at it. Will ask for your help if need be.
