### ISSUE TITLE
Uninstall guide for each component is missing

### ISSUE THREAD

**Issue by xwedu** [kubesphere/website#1591]
v3.1.0文档中无法搜索到卸载可插拔组件的操作方法

**Comment by FeynmanZhou** [comment]
@Patrick-LuoYu Can we prioritize this part of the documents? It has been frequently asked in the community.
/cc @kubesphere/sig-docs

**Comment by Felixnoo** [comment]
> @Patrick-LuoYu Can we prioritize this part of the documents? It has been frequently asked in the community.
> /cc @kubesphere/sig-docs

I'll add a document.
