### ISSUE TITLE
New namespace (kubesphere-devops-worker) for Jenkins agent

### ISSUE THREAD

**Issue by JohnNiang** [kubesphere/website#1616]
There have an upstream PR https://github.com/kubesphere/ks-installer/pull/1490 which will add a new namespace (kubesphere-devops-worker) in kubesphere v3.1.1. And also, we will change the namespace of `ks-devops-config` configmap  from `kubesphere-devops-system` into `kubesphere-devops-worker`.

I've provided a migration documentation about kubesphere v3.1.1 from <https://github.com/kubesphere/ks-installer/blob/a58ecb65f1735acbb1e852ac736d522d2e06cd85/docs/JenkinsUpgradeGuide.md>

Please adjust the website documentation according to the above information. If there is any information you need, I can provide it.

/area devops

**Comment by Felixnoo** [comment]
Is the ConfigMap `ks-devops-config` a new one in KS 3.1.1? I can't find it in the namespace `kubesphere-devops-system` in KS 3.1.0. Could you help me understand what are the changes to be reflected by adjusting documents?

**Comment by JohnNiang** [comment]
Hi @Felixnoo, <https://github.com/kubesphere/ks-installer/pull/1490> hasn't been released yet, please wait for a moment.

**Comment by Felixnoo** [comment]
@JohnNiang 
Hi, do we need to make updates in documents?

**Comment by JohnNiang** [comment]
> @JohnNiang Hi, do we need to make updates in documents?

Sure. 😄

**Comment by Felixnoo** [comment]
> > @JohnNiang Hi, do we need to make updates in documents?
> 
> Sure. 😄

@JohnNiang 
The configmap`ks-devops-config` you mentioned should be `ks-devops-agent`, and I already updated [the relevant document](https://kubesphere.io/docs/devops-user-guide/examples/use-nexus-in-pipelines/#step-3-modify-the-configmap).
I think we can close this issue.
/close
