### ISSUE TITLE
Wrong example with creating new service from s2i

### ISSUE THREAD

**Issue by LinuxSuRen** [kubesphere/website#1722]
As you can see from the following screenshot:

![image](https://user-images.githubusercontent.com/1450685/122041389-7ce0c700-ce0b-11eb-9992-6220d33cdbad.png)

Where I circled is a wrong example. Users will get an error tip, see also https://github.com/kubesphere/console/issues/1952

/priority high
/kind bug

**Comment by Felixnoo** [comment]
@LinuxSuRen 
I will change the images with the correct example. Besides, I think it is necessary to clarify in the document that only lower case letters are allowed here.

**Comment by LinuxSuRen** [comment]
> I think it is necessary to clarify in the document that only lower case letters are allowed here.

Please see also kubesphere/console#1952 . IMO it should be an improvement.

**Comment by Felixnoo** [comment]
> > I think it is necessary to clarify in the document that only lower case letters are allowed here.
> 
> Please see also [kubesphere/console#1952](https://github.com/kubesphere/console/issues/1952) . IMO it should be an improvement.

Sure. I'll just update the images with the correct example.
