### ISSUE TITLE
Typo in the document of KubeSphere advantages

### ISSUE THREAD

**Issue by rockpanda** [kubesphere/website#1733]
https://kubesphere.io/zh/docs/introduction/advantages/
设计愿景
Kubernetes 已经成为在私有云、**共有云**和混合云  是不是应该是**公有云**呢

**Comment by LinuxSuRen** [comment]
Hi @rockpanda , so glad to see you reporting this issue. If you like to do a contribution, please create a fix on [this file](https://github.com/kubesphere/website/edit/master/content/zh/docs/introduction/advantages.md).

We encourage everyone to communicate in English. I will help you to rewrite the issue title.

/retitle Typo in the document of KubeSphere advantages

**Comment by FeynmanZhou** [comment]
https://github.com/kubesphere/website/pull/1746 Thanks for your contribution! Fixed and closed.
