### ISSUE TITLE
SI2builder失败

### ISSUE THREAD

**Issue by cuiWT** [kubesphere/website#1832]
按照[指导文档](https://kubesphere.com.cn/docs/project-user-guide/image-builder/source-to-image/)创建一个服务
![Uploading 企业微信截图_8b791883-1aaf-4056-92de-e7cd647e4679.png…]()

没有像文档中预期的那样在镜像构建器生成一次构建

**Comment by zryfish** [comment]
Please go to our [forum](https://kubesphere.com.cn/forum) to get Chinese support, Github issues are English only.
