### ISSUE TITLE
Should "帐户" be modified to "账户"?

### ISSUE THREAD

**Issue by YANGMAO-ZHANG** [kubesphere/website#1836]
There is an blog to clarify why "帐户" is a wrong usage in Chinese (https://www.cnblogs.com/zdz8207/p/9583691.html). However, this is an one way of saying thing, would it be possible to invite you to have a discussion about it?

**Comment by Felixnoo** [comment]
/cc @kubesphere/sig-docs 
Hi team, please provide your thoughts on this issue.

**Comment by Felixnoo** [comment]
In documentation 3.2.0, we discard both words.
