### ISSUE TITLE
[OSSC] KubeSphere Document Translation Tasks

### ISSUE THREAD

**Issue by YANGMAO-ZHANG** [kubesphere/website#1854]
URL of the document: https://kubesphere.io/zh/docs/faq/multi-cluster-management/manage-multi-cluster/

I'm going to translate document of the manage-multi-cluster into Chinese. The URL of this document shown above.
 
![image](https://user-images.githubusercontent.com/51236151/127155285-18865ade-94f9-466a-ae45-0f3de7c82106.png)

**Comment by Felixnoo** [comment]
@YANGMAO-ZHANG 
Hi, thanks for creating this issue. Let's use this issue to track our document translation tasks. Please change the title of this issue to something like `[OSSC] KubeSphere Document Translation Tasks`.

**Comment by Felixnoo** [comment]
@YANGMAO-ZHANG 
Hi, please help translate [this document](https://kubesphere.io/zh/docs/installing-on-linux/public-cloud/install-kubesphere-on-azure-vms/). You can use the screenshots in EN for this task because we cannot operate on Azure. 
I suggest that, before you start translation, you follow [this quick](https://kubesphere.io/docs/quick-start/all-in-one-on-linux/) start to get a basic understanding of how to install KubeSphere.

**Comment by Felixnoo** [comment]
@YANGMAO-ZHANG 
Hi, please help translate [this document](https://kubesphere.io/zh/docs/installing-on-linux/introduction/vars/).

**Comment by Felixnoo** [comment]
@YANGMAO-ZHANG 
Hi, please help translate [this document](https://kubesphere.io/docs/devops-user-guide/how-to-use/jenkins-shared-library/).
You can read the other documents in this chapter to understand the DevOps concept before you start your translation.

**Comment by YANGMAO-ZHANG** [comment]
copy
------&nbsp;原始邮件&nbsp;------
***@***.***&gt;;
发送时间:2021年8月12日(星期四)&nbsp;上午10:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:Re:&nbsp;[kubesphere/website]&nbsp;[OSSC]&nbsp;KubeSphere&nbsp;Document&nbsp;Translation&nbsp;Tasks&nbsp;(#1854)



 
@YANGMAO-ZHANG
 Hi, please help translate this document.
 You can read the other documents in this chapter to understand the DevOps concept before you start your translation.
 
&mdash;
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Felixnoo** [comment]
@YANGMAO-ZHANG 
Hi, please help translate the following documents:

- [Document 1](https://kubesphere.io/docs/pluggable-components/uninstall-pluggable-components/)
- [Document 2](https://kubesphere.io/docs/devops-user-guide/examples/create-multi-cluster-pipeline/)
- [Document 3](https://kubesphere.io/docs/devops-user-guide/examples/use-nexus-in-pipelines/)

Take your time.

**Comment by YANGMAO-ZHANG** [comment]
Can you assign another 3 articles to me? Thanks

**Comment by YANGMAO-ZHANG** [comment]
Can you assign another 3 articles to me, please? Thanks.

**Comment by Felixnoo** [comment]
> Can you assign another 3 articles to me, please? Thanks.

Sure.

- [Document 1](https://kubesphere.io/docs/devops-user-guide/how-to-use/pipeline-webhook/)
- [Document 2](https://kubesphere.io/docs/project-user-guide/image-builder/s2i-and-b2i-webhooks/)
- [Document 3](https://kubesphere.io/docs/project-user-guide/image-builder/s2i-templates/)

**Comment by YANGMAO-ZHANG** [comment]
Hi, can I have another page to translate, it may take over 1 month, cause I have had many deadlines recently. Thanks

**Comment by Felixnoo** [comment]
> Hi, can I have another page to translate, it may take over 1 month, cause I have had many deadlines recently. Thanks

Hi, you can create a new issue and assign it to yourself to translate [this document](https://kubesphere.io/zh/docs/cluster-administration/cluster-settings/cluster-gateway/). Take your time.

**Comment by YANGMAO-ZHANG** [comment]
Hi, I have created a new issue.  Should I delete this issue?

**Comment by YANGMAO-ZHANG** [comment]
Can I create a new issue for the following translation task? Or, I have to create an issue for each task?

**Comment by YANGMAO-ZHANG** [comment]
> month
Hi, I have created a new issue. Should I delete this issue?

**Comment by YANGMAO-ZHANG** [comment]
> > Hi, can I have another page to translate, it may take over 1 month, cause I have had many deadlines recently. Thanks
> 
> Hi, you can create a new issue and assign it to yourself to translate [this document](https://kubesphere.io/zh/docs/cluster-administration/cluster-settings/cluster-gateway/). Take your time.

Hi, I have created a new issue. Should I delete this issue?

**Comment by YANGMAO-ZHANG** [comment]
> > Hi, can I have another page to translate, it may take over 1 month, cause I have had many deadlines recently. Thanks
> 
> Hi, you can create a new issue and assign it to yourself to translate [this document](https://kubesphere.io/zh/docs/cluster-administration/cluster-settings/cluster-gateway/). Take your time.

Can I create a new issue for the following translation task? Or, I have to create an issue for each task?

**Comment by Felixnoo** [comment]
> > > Hi, can I have another page to translate, it may take over 1 month, cause I have had many deadlines recently. Thanks
> > 
> > 
> > Hi, you can create a new issue and assign it to yourself to translate [this document](https://kubesphere.io/zh/docs/cluster-administration/cluster-settings/cluster-gateway/). Take your time.
> 
> Can I create a new issue for the following translation task? Or, I have to create an issue for each task?

@YANGMAO-ZHANG Hi, you have completed the translation tasks for the current documentation. I'll close this issue.

**Comment by Felixnoo** [comment]
Closing this issue as all the translation tasks are completed.
