### ISSUE TITLE
Glossary translation - Deployment

### ISSUE THREAD

**Issue by tang-wenfeng** [kubesphere/website#1859]
【容器镜像设置】文档中，Deployment翻译为“部署”，结合前文创建部署，可能会导致歧义（创建且部署）；是否可以对应StatefulSet的“有状态副本集”，改叫做“无状态副本集”？

**Comment by Felixnoo** [comment]
Hi, thanks for your feedback. We understand your concern and will update the document you mentioned to work around this issue. 
Currently, Kubernetes concepts like Deployment, StatefulSet, and DaemonSet are all translated into Chinese in KubeSphere documentation. These translations do make confusions sometimes. We will keep looking into this and try to come up with a better solution.
