### ISSUE TITLE
Is it possible to add some docs like 'how to use casbin in kubesphere' in kubesphere doc?

### ISSUE THREAD

**Issue by ComradeProgrammer** [kubesphere/website#1884]
I am a junior member of 'casbin' community. Our community just developed a plugin for kubesphere, which implemented some tiny functions. I am wondering is it possible to add some docs about the usage of this plugin on kubesphere website? And if the answer is not negative, what should I do to futher? Is there any rules or examples to follow?

 I am actually new to open-source world, so actually I am not sure whether it is normal to post such an issue , or whether it's correct to post this issue here. Please pardon me if anything goes wrong.

 If you want to know what the 'casbin' is, see <https://casbin.org/docs/zh-CN/overview>

 If you want to know what the plugin is, see <https://github.com/casbin/kubesphere-authz>

**Comment by sagilio** [comment]
@ComradeProgrammer It looks great! Actually, we are planning how to integrate Gatekeeper and Casbin as a part of kubesphere. I think we can discuss together how to implement it.
