### ISSUE TITLE
For md files in case studies, how can multiple paragraphs be put under the same title?

### ISSUE THREAD

**Issue by Sherlock113** [kubesphere/website#19]
For the same section, it contains title, content and image. Paragraphs are put under "content", but currently only one paragraph can be put under "content". What if multiple paragraphs need to be included under the same title?

**Comment by liuboaibc** [comment]
i will replace the 'content' with a list. @Sherlock113

**Comment by Sherlock113** [comment]
This issue was solved and now multiple paragraphs can be added. However, it seems that the English colon (:) cannot be added in either the title or the paragraph. If a colon is included, it says "failed to unmarshal YAML: yaml: line 28: mapping values are not allowed in this context" when "hugo server -D" is used.

**Comment by liuboaibc** [comment]
you can add single (‘ ’) or double (“ ”),example:
```
- content: "your content......"
```
@Sherlock113

**Comment by Sherlock113** [comment]
Solved. Thx.
