### ISSUE TITLE
YouTube Channel link could be nicer

### ISSUE THREAD

**Issue by karuppiah7890** [kubesphere/website#1953]
Currently the YouTube channel link in the website points to https://www.youtube.com/channel/UCyTdUQUYjf7XLjxECx63Hpw which when looked at doesn't look very great. An alternate link is https://www.youtube.com/c/KubeSphere which looks nicer with the name `KubeSphere` without any random characters

Note: Beware that https://www.youtube.com/channel/KubeSphere link does **NOT** work and gives 404

**Comment by FeynmanZhou** [comment]
Thanks for your suggestion! It's helpful! Would you like to raise a PR to replace it with `https://www.youtube.com/c/KubeSphere`?

**Comment by karuppiah7890** [comment]
Sure! 👍
