### ISSUE TITLE
Do We Need the Document: Import Kubeadm Kubernetes Cluster

### ISSUE THREAD

**Issue by Felixnoo** [kubesphere/website#2003]
Currently, a document titled [Import Kubeadm Kubernetes Cluster](https://kubesphere.io/docs/multicluster-management/import-on-prem-k8s/import-kubeadm-k8s/) is TBD under the Multi-cluster Management chapter.

As I understand it, importing a Kubeadm Kubernetes cluster has to use either the [Direct Connection](https://kubesphere.io/docs/multicluster-management/enable-multicluster/direct-connection/) or [Agent Connection](https://kubesphere.io/docs/multicluster-management/enable-multicluster/agent-connection/), and we already have the corresponding documents explaining these importing methods.

Therefore, I am wondering whether we need a document titled Import Kubeadm Kubernetes Cluster or not?

@zryfish 
@FeynmanZhou 
What do you think?

**Comment by FeynmanZhou** [comment]
@Felixnoo Sorry for missing this issue. I think we can remove this doc and add an introduction in the KubeSphere Federation guide for this scenario. Now it is a blank page that puzzles a lot of users. 

/cc @kubesphere/sig-multicluster
