### ISSUE TITLE
ingress有什么意义

### ISSUE THREAD

**Issue by imaoxian** [kubesphere/website#2017]
不明白为什么配置ingress，还必须加个外网访问网关，这个网关就是暴露NodePort，那还有什么意义，我直接暴露service的Nodeport不就行了？还可以指定端口号，ingress的意义不就是能把ClusterIP的端口暴露出去吗？

**Comment by mafeifan** [comment]
为了负载均衡？

**Comment by FeynmanZhou** [comment]
Please take a look at https://kubesphere.io/docs/project-user-guide/application-workloads/routes/
