### ISSUE TITLE
can't Download offline-installation-tool.sh

### ISSUE THREAD

**Issue by copenbusiness** [kubesphere/website#2042]
the guide https://kubesphere.io/docs/installing-on-linux/introduction/air-gapped-installation/

Download offline-installation-tool.sh.:
curl -L -O https://github.com/kubesphere/ks-installer/releases/download/v3.2.0/offline-installation-tool.sh

after runnng the command ,the message dispaly "can't find file".
but can run the followng command:
curl -L -O https://github.com/kubesphere/ks-installer/releases/download/v3.1.1/offline-installation-tool.sh

**Comment by pixiake** [comment]
@copenbusiness Thanks for the feedback. The script `offline-installation-tool.sh` has been added to v3.2.0 release. Please try it again.

**Comment by copenbusiness** [comment]
@pixiake : Thanks you.
Now I can run the command.
[root@master work]# curl -L -O https://github.com/kubesphere/ks-installer/releases/download/v3.2.0/offline-installation-tool.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   636  100   636    0     0     88      0  0:00:07  0:00:07 --:--:--   185
100  6752  100  6752    0     0    647      0  0:00:10  0:00:10 --:--:--  3930
[root@master work]#

**Comment by copenbusiness** [comment]
now it can download the file.
