### ISSUE TITLE
The webhook configuration doc is missing a Chinese version

### ISSUE THREAD

**Issue by xiaokangshuai** [kubesphere/website#2058]
文档告警渠道的webhook内容为空

**Comment by FeynmanZhou** [comment]
You can check out the [English version](https://v3-1.docs.kubesphere.io/docs/cluster-administration/platform-settings/notification-management/configure-webhook/). The [Chinese page](https://v3-1.docs.kubesphere.io/zh/docs/cluster-administration/platform-settings/notification-management/configure-webhook/) is waiting for someone who could help us to translate and contribute to the website.

**Comment by FeynmanZhou** [comment]
@123liubao Thanks for your help! 👍

**Comment by FeynmanZhou** [comment]
@123liubao Thanks for your help! 👍
