### ISSUE TITLE
Request to add restriction about the DevOps CD feature

### ISSUE THREAD

**Issue by LinuxSuRen** [kubesphere/website#2096]
Provide a restriction statement for the DevOps CD feature.

## Background

Since v3.0.0, in the DevOps component, the version of Jenkins plugin [kubernets-cd](https://github.com/jenkinsci/kubernetes-cd-plugin) is [2.3.1](https://github.com/kubesphere/ks-jenkins/blob/24fb9dc88d668e82782f06ae342a93e3a53345c5/formula.yaml#L248). You will find out it is out of maintenance if you try to see the commit history of it. The [last release commit](https://github.com/jenkinsci/kubernetes-cd-plugin/commit/df00e42bbac60253fd311165b0765cca19e4b097) was in the last year.

As we mentioned in https://github.com/kubesphere/ks-devops/issues/137, we don't have any strong reason to keep using this solution anymore. Please keep reading the following content if you want to know more details.

[kubernetes-cd-plugin](https://github.com/jenkinsci/kubernetes-cd-plugin/blob/df00e42bbac60253fd311165b0765cca19e4b097/pom.xml#L29) relies on the Kubernetes Java client. [For this version](https://github.com/kubernetes-client/java/tree/release-7.0.0#compatibility), it can keep compatible from Kubernetes 1.9 to 1.15. Make it be short, please notice the version of your Kubernetes cluster before using it.

## Conclusion

* Put a known issue. Please make sure your Kubernetes cluster version is in the range from 1.9 to 1.15 before using the following CD feature.
* Provide an alternative solution.

![image](https://user-images.githubusercontent.com/1450685/141136941-cd63aac1-96a6-4c0b-93c4-cbef7a2ba3c9.png)

## Alternative

You can use kubectl to deploy your desired application into a cluster. For instance, you can learn from the following snippet:

```groovy
    stage('deploy') {
      steps {
        container ('base') {
          sh '''
          kubectl apply -f your-crd-file.yaml
          '''
        }
      }
```

- [ ] Please follow our new simple kubectl-based demo if you still it's hard to understand what should do.

## FAQ

* Is that possible to use a GitOps framework to deploy my applications?
  * Yes, totally. You can definitely adapt it, such as Argo CD. But you might need to [deploy Argo CD](https://argo-cd.readthedocs.io/en/stable/getting_started/) by yourself before we [support it out-of-box](https://github.com/kubesphere/ks-devops/issues/63).

/area devops

**Comment by Felixnoo** [comment]
I think we can track all the PRs that update DevOps documents in order to respond, directly or indirectly, to the request in this issue.

**Comment by JohnNiang** [comment]
I think this issue has been resolved, please refer to
- https://github.com/kubesphere/console/issues/2612
- https://github.com/kubesphere/website/pull/2098
- https://github.com/kubesphere/website/pull/2187
- https://github.com/kubesphere/devops-maven-sample/issues/4

I'm going to close this issue.
/close
