### ISSUE TITLE
doc is missing

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/website#211]
The link to port requirements is missing. https://kubesphere.io/docs/quick-start/all-in-one-on-linux/
![Screen Shot 2020-09-03 at 9 56 18 AM](https://user-images.githubusercontent.com/28859385/92062961-8644f980-edcc-11ea-9f8d-2b9bf20f3c2b.png)

**Comment by rayzhou2017** [comment]
I am going to update it to https://github.com/kubesphere/kubekey/blob/master/docs/network-access.md

**Comment by FeynmanZhou** [comment]
@rayzhou2017 Porter Requirements: https://kubesphere.io/docs/installing-on-linux/introduction/port-firewall/

**Comment by rayzhou2017** [comment]
Yes, I just see it, but why there is network access in the same doc link to the github? Also is the change not uploaded to online in real time?
