### ISSUE TITLE
3.2.0的离线包  哪里有啊

### ISSUE THREAD

**Issue by Immortals007** [kubesphere/website#2128]
3.2.0的离线包  哪里有啊

**Comment by zryfish** [comment]
English only, please! v3.2.0 offline installation isn't available now. 
/close

**Comment by FeynmanZhou** [comment]
@Immortals007 Hi, 

You can try the air-gapped installation through this [guide](https://kubesphere.io/zh/docs/installing-on-linux/introduction/air-gapped-installation/). 

As we are going to publish the v3.2.1 by the end of this month, the offline installer will be available in December. Sorry for the delay.
