### ISSUE TITLE
Install KubeSphere on Minikube

### ISSUE THREAD

**Issue by FeynmanZhou** [kubesphere/website#2134]
As we can see from the CNCF survey 2020, Minikube is the most popular Kubernetes environment among users. We have been tested KubeSphere installation on some lightweight K8s distros such as [K3s](https://kubesphere.io/zh/docs/installing-on-linux/on-premises/install-kubesphere-and-k3s/) and [KinD](https://kubesphere.com.cn/forum/d/1673-kind-kubernetes-kubesphere) before, but we have never tried KubeSphere on Minikube. 

We hope it KubeSphere could be run successfully on Minikube as well, and create an installation guide to instruct users to set up KubeSphere on their local laptop with Minikube.

If you are interested in helping us to test it and contribute a document to the website, please leave your comment below. Thanks!

![image](https://user-images.githubusercontent.com/40452856/142715681-30d155fb-6918-490f-8bbd-bd2a82cbe82c.png)

**Comment by eliaskoromilas** [comment]
FYI we test KubeSphere deployments on Minikube/MicroK8s all the time!

**Comment by FeynmanZhou** [comment]
> FYI we test KubeSphere deployments on Minikube/MicroK8s all the time!

@eliaskoromilas Good news! Thanks for letting us know!

**Comment by JayL-zxl** [comment]
> 仅供参考，我们一直在 Minikube/MicroK8s 上测试 KubeSphere 部署！

.it means this issue its doesn't needed?

**Comment by FeynmanZhou** [comment]
> > 仅供参考，我们一直在 Minikube/MicroK8s 上测试 KubeSphere 部署！
> 
> .it means this issue its doesn't needed?

It means it works on Minikube as we expected. You can still prepare for the guide.

**Comment by JayL-zxl** [comment]
okay

**Comment by enraiha0307** [comment]
Hi, @FeynmanZhou I have written the steps for "installing-kubesphere-on-minikube". Most of them were similar to [Installing Kubesphere on Kubernetes](https://kubesphere.io/docs/quick-start/minimal-kubesphere-on-k8s/ ) steps. So I added the Prerequisite version checks needed for minikube and included code snippets with terminal output.
Following the similar structure as in [Installing Kubesphere on Kubernetes](https://kubesphere.io/docs/quick-start/minimal-kubesphere-on-k8s/ ), Do I need to include a video demonstration or just a code demonstration will be enough?

**Comment by FeynmanZhou** [comment]
> 

Both are fine, the video demonstration seems much better. We could reference your video or guide in the community.
