### ISSUE TITLE
spelling mistake

### ISSUE THREAD

**Issue by showjason** [kubesphere/website#2229]
![image](https://user-images.githubusercontent.com/27723125/147382441-ed8987b0-ce1d-4162-a9c4-f4d48ba3fce9.png)

As title, I think it should be `until` in [Create a Jenkins Pipeline Using a Jenkinsfile](https://v3-1.docs.kubesphere.io/docs/devops-user-guide/how-to-use/create-a-pipeline-using-jenkinsfile/)

**Comment by FeynmanZhou** [comment]
> ![image](https://user-images.githubusercontent.com/27723125/147382441-ed8987b0-ce1d-4162-a9c4-f4d48ba3fce9.png)
> 
> As title, I think it should be `until` in [Create a Jenkins Pipeline Using a Jenkinsfile](https://v3-1.docs.kubesphere.io/docs/devops-user-guide/how-to-use/create-a-pipeline-using-jenkinsfile/)

You are right, this is a typo. Are you interested in helping us to fix it?

**Comment by Felixnoo** [comment]
Issue fixed.
