### ISSUE TITLE
The install ceph doc is missing a chinese version

### ISSUE THREAD

**Issue by 123liubao** [kubesphere/website#2256]
https://kubesphere.io/zh/docs/installing-on-linux/persistent-storage-configurations/install-ceph-csi-rbd/

The doc of `Install Ceph`  need to be translated.

**Comment by Bettygogo2021** [comment]
@123liubao Sorry for the late reply. I thought this issue had been fixed. I am wondering if you are available to translate this doc. If not, I will translate it as soon as possible. Thx for your notice.
