### ISSUE TITLE
The Devops pipeline has no webhook configuration

### ISSUE THREAD

**Issue by liangjw-china** [kubesphere/website#2266]
According to the official documentation, the webook configuration was not found in the pipeline configuration.
kubesphere version：v3.2.0

**Comment by Felixnoo** [comment]
Hi, which document are you referring to here?

**Comment by liangjw-china** [comment]
Here    https://kubesphere.io/zh/docs/devops-user-guide/how-to-use/pipeline-webhook/

**Comment by Felixnoo** [comment]
> Here https://kubesphere.io/zh/docs/devops-user-guide/how-to-use/pipeline-webhook/

You have to use a repository to create a pipeline so that you can use webhook.
![image](https://user-images.githubusercontent.com/75110798/149297626-6c572740-5a1b-47dd-916b-7bff76919e1d.png)

/cc @kubesphere/sig-devops  Please correct me if I miss anything.

**Comment by liangjw-china** [comment]
OK,thanks,but wouldn't this requirement seem inflexible?
