### ISSUE TITLE
[Translation] Cluster Gateway

### ISSUE THREAD

**Issue by YANGMAO-ZHANG** [kubesphere/website#2269]
Open source document translation

**Comment by YANGMAO-ZHANG** [comment]
URL: https://kubesphere.io/docs/cluster-administration/cluster-settings/cluster-gateway/

**Comment by Felixnoo** [comment]
Issue fixed, and thanks for your contribution.

**Comment by Felixnoo** [comment]
BTW, we are planning to create new issues for future translations so that you don't have to create issues by yourself. Please stay tuned~
