### ISSUE TITLE
The Service Accounts doc is missing a chinese version

### ISSUE THREAD

**Issue by 123liubao** [kubesphere/website#2297]
https://kubesphere.io/zh/docs/project-user-guide/configuration/serviceaccounts/

The doc of  `Service Accounts` need to be translated.

**Comment by FeynmanZhou** [comment]
Thanks for reporting this issue. Are you interested in helping our community to provide a Chinese version for it?

**Comment by 123liubao** [comment]
> Thanks for reporting this issue. Are you interested in helping our community to provide a Chinese version for it?

sure~

**Comment by Felixnoo** [comment]
> > Thanks for reporting this issue. Are you interested in helping our community to provide a Chinese version for it?
> 
> sure~

@123liubao Hi, thanks for your interest, but an existing PR #2260 is dealing with the same issue.
