### ISSUE TITLE
docs:correct the chinese version of release-note for 3.2.0

### ISSUE THREAD

**Issue by 123liubao** [kubesphere/website#2307]
https://kubesphere.io/zh/docs/release/release-v320/

In this doc, 'cluster' is translated to '群集' , maybe this should be changed to '集群'

**Comment by Felixnoo** [comment]
Good catch! Can you create a PR to fix this bug?

**Comment by 123liubao** [comment]
> Good catch! Can you create a PR to fix this bug?

Sure!
