### ISSUE TITLE
node  machines number is Incorrect

### ISSUE THREAD

**Issue by Feeeenng** [kubesphere/website#2321]
the document descriptiion 6 node, actually only five node.

`https://kubesphere.com.cn/docs/installing-on-linux/high-availability-configurations/internal-ha-configuration/#%E6%9E%B6%E6%9E%84`

issue image:
![image](https://user-images.githubusercontent.com/14897634/155844706-612c58a1-d33c-4892-b21f-86e34f1bdabe.png)

**Comment by Bettygogo2021** [comment]
Thx for your suggestion. I discussed it with the developer, and it turns out the architecture is for example only and does not need to be 3 master nodes and 3 worker nodes. Anyway, I'll rewrite this part to make it less confusing.
