### ISSUE TITLE
Add a prerequisite for CPU architecture when installing KubeSphere on Linux machines or K8s clusters

### ISSUE THREAD

**Issue by FeynmanZhou** [kubesphere/website#2325]
The prerequisite for CPU architecture is not mentioned in the installation guides. Currently, KubeSphere 3.2.1 only supports installation on AMD64 machines, see https://github.com/kubesphere/kubesphere/issues/4693. We should add a prerequisite for CPU architecture in the documentation.

**Comment by Bettygogo2021** [comment]
ok, i'll fix it.
