### ISSUE TITLE
流水线能否备份呢？

### ISSUE THREAD

**Issue by freemankevin** [kubesphere/website#2334]
我需要一键或多选导出或能做定期备份那种。

**Comment by freemankevin** [comment]
![image](https://user-images.githubusercontent.com/71524776/157148000-219862fc-c5ee-4b9e-9f59-c2436a3de78f.png)
上面加几个功能按钮？

**Comment by FeynmanZhou** [comment]
IMO, it might be supported by [DRaaS](https://kubesphere.cloud/self-service/disaster-recovery/).
