### ISSUE TITLE
Need update document about offline-installation-tool.sh

### ISSUE THREAD

**Issue by rikkartx** [kubesphere/website#2340]
In [Air-gapped Installation Step 4](https://kubesphere.io/docs/installing-on-linux/introduction/air-gapped-installation/#step-4-prepare-installation-images) I got information about `offline-installation-tool.sh`: 
``` sh
root@master:/home/ubuntu# ./offline-installation-tool.sh -h
Usage:
   
  ./offline-installation-tool.sh [-l IMAGES-LIST] [-d IMAGES-DIR] [-r PRIVATE-REGISTRY] [-v KUBERNETES-VERSION ]
   
Description:
  -b                     : save kubernetes' binaries.
  -d IMAGES-DIR          : the dir of files (tar.gz) which generated by `docker save`. default: ./kubesphere-images
  -l IMAGES-LIST         : text file with list of images.
  -r PRIVATE-REGISTRY    : target private registry:port.
  -s                     : save model will be applied. Pull the images in the IMAGES-LIST and save images as a tar.gz file.
  -v KUBERNETES-VERSION  : download kubernetes' binaries. default: v1.17.9
  -h                     : usage message

```
But when I download script and execute `./offline-installation-tool.sh -h`, I got: 
``` sh
Usage:

  ./offline-installation-tool.sh [-l IMAGES-LIST] [-d IMAGES-DIR] [-r PRIVATE-REGISTRY] [-v KUBERNETES-VERSION ]

Description:
  -b                     : save kubernetes' binaries.
  -d IMAGES-DIR          : the dir of files (tar.gz) which generated by `docker save`. default: /Users/rikka/Desktop/kubesphere/kubesphere-images
  -l IMAGES-LIST         : text file with list of images.
  -r PRIVATE-REGISTRY    : target private registry:port.
  -s                     : save model will be applied. Pull the images in the IMAGES-LIST and save images as a tar.gz file.
  -h                     : usage message

Examples:

# Download the default kubernetes version dependency binaries.(default: [kubernetes: v1.21.5], [helm: v3.6.3], [cni: v0.9.1], [etcd: v3.4.13])
./offline-installtion-tool.sh -b

# Custom download the kubernetes version dependecy binaries.
export KUBERNETES_VERSION=v1.22.1;export HELM_VERSION=v3.6.3;
./offline-installtion-tool.sh -b
```
There is no `-v` flag in usage, and executing the following command `./offline-installation-tool.sh -b -v v1.21.5` will repeat print usage information in console. So I think that's a mistake in this chapter.

**Comment by FeynmanZhou** [comment]
@rikkartx Thanks for your feedback! I see the doc has been updated. Could you pls help to verify it? If you think it's resolved, this issue will be closed.

**Comment by rikkartx** [comment]
@FeynmanZhou  Nothing changed, there's still no `-v` flag in script 😂
<img width="1566" alt="Screen Shot 2022-03-28 at 8 22 51 AM" src="https://user-images.githubusercontent.com/27550824/160307935-1ab6d05c-dc1b-4636-bcbe-2a73cd35bb26.png">

**Comment by rikkartx** [comment]
Thanks for your guys efforts 🎉. This chapter seems to have a lot of changes, I will reread this chapter asap.

**Comment by FeynmanZhou** [comment]
> Thanks for your guys efforts 🎉. This chapter seems to have a lot of changes, I will reread this chapter asap.

You are welcome. Feel free to report any issues to us : )
