### ISSUE TITLE
Need change the KubeKey download command

### ISSUE THREAD

**Issue by 24sama** [kubesphere/website#2346]
On the website, the KubeKey download command is:
```
curl -sfL https://get-kk.kubesphere.io | VERSION=v1.2.1 sh -
```
At present, kk v2.0.0 is already released, and this command will lead users to download the old kk version. 
I suggest changing it to:
```
curl -sfL https://get-kk.kubesphere.io | sh -
```
This command will always download the latest version.

Besides, I think we need to add a new official offline installation guide document. 
https://kubesphere.io/docs/installing-on-linux/introduction/air-gapped-installation/

**Comment by 24sama** [comment]
link https://github.com/kubesphere/website/issues/2340

/cc @kubesphere/sig-docs

**Comment by Bettygogo2021** [comment]
ok, thx, i'll fix it.
