### ISSUE TITLE
aws eks 安装 kubesphere 完成后, 从web console 登陆修改配置, 导致服务停止

### ISSUE THREAD

**Issue by linzea** [kubesphere/website#2361]
https://kubesphere.com.cn/docs/installing-on-kubernetes/hosted-kubernetes/install-kubesphere-on-eks/#%E5%90%AF%E7%94%A8%E5%8F%AF%E6%8F%92%E6%8B%94%E7%BB%84%E4%BB%B6%E5%8F%AF%E9%80%89

我按照这个步骤启动了 eks 集群和 kubesphere , 初始化后登陆 web, 启动 devops  kubesphere 会停止工作, 
# kubectl edit svc ks-console -n kubesphere-system  修改过的 ks-console 也会被重置,  
再次修改成 LoadBalancer web console 密码无法登陆, 重置密码也无效

**Comment by FeynmanZhou** [comment]
Hi @linzea ,

Can you inspect the workloads under ns `kubesphere-system`? You could try `kubectl get pod -n kubesphere-system`.

**Comment by linzea** [comment]
NAME                                     READY   STATUS    RESTARTS   AGE
ks-apiserver-577c5d479b-l682w            1/1     Running   0          2m21s
ks-console-65f4d44d88-d7nr5              1/1     Running   0          66m
ks-controller-manager-7c79cc6956-cnkng   1/1     Running   0          2m21s
ks-installer-85dcfff87d-v84jf            1/1     Running   0          66m
minio-859cb4d777-g87g2                   1/1     Running   0          66m
openldap-0                               1/1     Running   0          66m

**Comment by FeynmanZhou** [comment]
Have you fixed it by yourself?
