### ISSUE TITLE
文档地址无法跳转

### ISSUE THREAD

**Issue by MemoryF** [kubesphere/website#2363]
https://kubesphere.com.cn/docs/access-control-and-account-management/external-authentication/set-up-external-authentication/

点击文末的

[CAS Identity Provider](https://kubesphere.com.cn/docs/access-control-and-account-management/external-authentication/set-up-external-authentication/)  跳转的是当前地址

**Comment by FeynmanZhou** [comment]
Hi @kubesphere/sig-docs @kubesphere/sig-multitenancy  ,

Could you please help to take a look at this issue? Thanks

**Comment by Bettygogo2021** [comment]
We are fixing this issue in 3.3 by adding more reference materials. Thx for your suggestions❀
