### ISSUE TITLE
Suggestion: Add word in the search bar

### ISSUE THREAD

**Issue by Sherlock113** [kubesphere/website#241]
Now there is nothing in the search bar while I am wondering if we can add some words here.
![截屏2020-09-07下午6 25 07](https://user-images.githubusercontent.com/65327072/92377911-7bc19180-f137-11ea-98fd-f699228a36c5.png)

For example, in Openshift search bar it displays "Search Documentation".
![截屏2020-09-07下午5 07 27](https://user-images.githubusercontent.com/65327072/92377981-93991580-f137-11ea-97bf-dd4e807229e0.png)

In Google Documentation, it is "Search".
![截屏2020-09-07下午5 06 14](https://user-images.githubusercontent.com/65327072/92378050-b6c3c500-f137-11ea-8e84-4707ffd7a3fe.png)

Just a suggestion here, not a must.

**Comment by FeynmanZhou** [comment]
@Sherlock113  Is this word ok?
https://deploy-preview-245--kubesphere-v3.netlify.app/docs/

![image](https://user-images.githubusercontent.com/40452856/92558980-45545580-f2a2-11ea-9eb9-6243b0687c2e.png)

**Comment by Sherlock113** [comment]
I prefer to use words like "Search Documentation" as I notice in the website of major cloud providers, the words in the search bar are quite short and obvious. For example:

Google: Search
OpenShift: Search Documentation
IBM: Search IBM Cloud documentation
Oracle: Search
Microsoft Docs: Search

"Enter keywords to get help quickly" is absolutely correct here, but I think it may be better if we can follow the way others do. The main reason for putting some words here is just to tell our readers this is the search bar.

**Comment by FeynmanZhou** [comment]
Updated.
