### ISSUE TITLE
Request: Add 'Copied' acknowledment when the commands/code is copied. 

### ISSUE THREAD

**Issue by karnatisrinivas** [kubesphere/website#2442]
<img width="910" alt="Screenshot 2022-05-18 at 6 12 15 PM" src="https://user-images.githubusercontent.com/52213014/169041395-aef2c4cb-7d62-44e8-9fbd-56b122dc4d7f.png">
Commands in the site can be copied but when It doesn't show any acknowledgement stating the command 'copied'. It would be nice if user get to know if copied is copied or not?

**Comment by FeynmanZhou** [comment]
Hi @Arhell ,

Would you please help to support this feature?
