### ISSUE TITLE
All-in-One安装异常

### ISSUE THREAD

**Issue by fatherfox** [kubesphere/website#2488]
操作系统：Ubuntu 20.04.4 LTS
docker：20.10.14

执行 ./kk create cluster --with-kubernetes v1.21.5 --with-kubesphere v3.2.1

最终异常
Then you can join any number of worker nodes by running the following on each as root:

kubeadm join lb.kubesphere.local:6443 --token 708ymb.l0s7sxn3829lykd2 \
        --discovery-token-ca-cert-hash sha256:ed38e7ce56df9513396f5c73dba1dc6fbfea57cef5cd9744ea758627ab44c7db
11:42:32 CST success: [wangheng-ThinkPad-T430]
11:42:32 CST [InitKubernetesModule] Copy admin.conf to ~/.kube/config
11:42:32 CST success: [wangheng-ThinkPad-T430]
11:42:32 CST [InitKubernetesModule] Remove master taint
11:42:34 CST stdout: [wangheng-ThinkPad-T430]
Error from server (NotFound): nodes "wangheng-ThinkPad-T430" not found
11:42:34 CST message: [wangheng-ThinkPad-T430]
remove master taint failed: Failed to exec command: sudo -E /bin/bash -c "/usr/local/bin/kubectl taint nodes wangheng-ThinkPad-T430 node-role.kubernetes.io/master=:NoSchedule-"
Error from server (NotFound): nodes "wangheng-ThinkPad-T430" not found: Process exited with status 1
11:42:34 CST retry: [wangheng-ThinkPad-T430]
11:42:39 CST stdout: [wangheng-ThinkPad-T430]
Error from server (NotFound): nodes "wangheng-ThinkPad-T430" not found
11:42:39 CST message: [wangheng-ThinkPad-T430]
remove master taint failed: Failed to exec command: sudo -E /bin/bash -c "/usr/local/bin/kubectl taint nodes wangheng-ThinkPad-T430 node-role.kubernetes.io/master=:NoSchedule-"
Error from server (NotFound): nodes "wangheng-ThinkPad-T430" not found: Process exited with status 1
11:42:39 CST retry: [wangheng-ThinkPad-T430]
11:42:44 CST stdout: [wangheng-ThinkPad-T430]
Error from server (NotFound): nodes "wangheng-ThinkPad-T430" not found
11:42:44 CST message: [wangheng-ThinkPad-T430]
remove master taint failed: Failed to exec command: sudo -E /bin/bash -c "/usr/local/bin/kubectl taint nodes wangheng-ThinkPad-T430 node-role.kubernetes.io/master=:NoSchedule-"
Error from server (NotFound): nodes "wangheng-ThinkPad-T430" not found: Process exited with status 1
11:42:44 CST retry: [wangheng-ThinkPad-T430]
11:42:49 CST stdout: [wangheng-ThinkPad-T430]
Error from server (NotFound): nodes "wangheng-ThinkPad-T430" not found
11:42:49 CST message: [wangheng-ThinkPad-T430]
remove master taint failed: Failed to exec command: sudo -E /bin/bash -c "/usr/local/bin/kubectl taint nodes wangheng-ThinkPad-T430 node-role.kubernetes.io/master=:NoSchedule-"
Error from server (NotFound): nodes "wangheng-ThinkPad-T430" not found: Process exited with status 1
11:42:49 CST retry: [wangheng-ThinkPad-T430]
11:42:54 CST stdout: [wangheng-ThinkPad-T430]
Error from server (NotFound): nodes "wangheng-ThinkPad-T430" not found
11:42:54 CST message: [wangheng-ThinkPad-T430]
remove master taint failed: Failed to exec command: sudo -E /bin/bash -c "/usr/local/bin/kubectl taint nodes wangheng-ThinkPad-T430 node-role.kubernetes.io/master=:NoSchedule-"
Error from server (NotFound): nodes "wangheng-ThinkPad-T430" not found: Process exited with status 1
11:42:54 CST failed: [wangheng-ThinkPad-T430]
error: Pipeline[CreateClusterPipeline] execute failed: Module[InitKubernetesModule] exec failed:
failed: [wangheng-ThinkPad-T430] [RemoveMasterTaint] exec failed after 5 retires: remove master taint failed: Failed to exec command: sudo -E /bin/bash -c "/usr/local/bin/kubectl taint nodes wangheng-ThinkPad-T430 node-role.kubernetes.io/master=:NoSchedule-"
Error from server (NotFound): nodes "wangheng-ThinkPad-T430" not found: Process exited with status 1

**Comment by lizhongyuan3** [comment]
hostname 不能包含大写字母

**Comment by lizhongyuan3** [comment]
修改hostname 为 wangheng-thinkpad-t430 试试
