### ISSUE TITLE
KubeSphere API文档中生成令牌的地方少了一个反斜杠

### ISSUE THREAD

**Issue by liu01100115** [kubesphere/website#2597]
文档：https://kubesphere.com.cn/docs/v3.3/reference/api-docs/#%E4%BD%BF%E7%94%A8-kubesphere-api

文档中生成令牌的地方少了一个反斜杠

![image](https://user-images.githubusercontent.com/32833737/181154340-a0f83b4d-4967-48b0-9af0-63a50364cafa.png)

**Comment by Bettygogo2021** [comment]
@liu01100115 Hi, thx for spotting this omission. I've updated the doc, and your suggestions are always welcome.👏🏻
