### ISSUE TITLE
url page error

### ISSUE THREAD

**Issue by jetluo** [kubesphere/website#2789]
when open the url
 https://kubesphere.io/zh/docs/v3.3/devops-user-guide/
then click
<img width="1431" alt="image" src="https://user-images.githubusercontent.com/11695434/209110860-dc01c4f8-2365-49ed-b5fd-552cd0cf3128.png">
while get the error url 

https://kubesphere.io/zh/docs/v3.3/h/docs/v3.3/h/docs/v3.3/h/docs/v3.3/h/docs/v3.3/h/docs/v3.3/h/docs/v3.3/h/docs/v3.3/h/docs/v3.3/h/docs/v3.3/h/docs/v3.3/h/docs/v3.3/h/docs/v3.3/h/docs/v3.3/h/docs/v3.3/h/docs/v3.3/

**Comment by enraiha0307** [comment]
I think this issue has been fixed. I checked it just now.
