### ISSUE TITLE
中文文档串行

### ISSUE THREAD

**Issue by nxdong** [kubesphere/website#2817]
页面： https://kubesphere.io/zh/docs/v3.3/quick-start/all-in-one-on-linux/

"硬件推荐配置" 标题下的表格内容串行。
如图：
![Screenshot from 2023-01-31 10-48-14](https://user-images.githubusercontent.com/6704315/215650192-ac52d78f-c02b-4f7a-aa79-395fd4542aa6.png)

**Comment by faweizhao26** [comment]
Is this problem solved? What browser are you using?

**Comment by nxdong** [comment]
this problem solved.
