### ISSUE TITLE
update error page.

### ISSUE THREAD

**Issue by freemankevin** [kubesphere/website#2823]
https://v3-1.docs.kubesphere.io/docs/project-administration/project-gateway/

![image](https://user-images.githubusercontent.com/71524776/217172634-ea026081-7fb1-433b-b7ef-94022ed04599.png)

![image](https://user-images.githubusercontent.com/71524776/217172582-8693f419-bc6f-41a7-b683-363e995b8d05.png)

**Comment by faweizhao26** [comment]
This broken link has been fixed, please check once.

**Comment by freemankevin** [comment]
![image](https://user-images.githubusercontent.com/71524776/224363759-f6fc633f-3cff-4360-a685-0fdadbfebcfc.png)
Isn't it the nginx official f5 rule problem?

**Comment by faweizhao26** [comment]
This problem is already been solved. So I close this issue now.
