### ISSUE TITLE
error: Unsupported KubeSphere version: v3.3.2

### ISSUE THREAD

**Issue by dinghao2020** [kubesphere/website#2856]
./kk create cluster -f config-sample.yaml
error: Unsupported KubeSphere version: v3.3.2

**Comment by cattivik39** [comment]
Hi,
I have kubesphere v3.3.1 and when
./kk upgrade --with-kubernetes v1.24.8 --with-kubesphere v3.3.2 -f config-sample.yaml
error: Unsupported KubeSphere version: v3.3.2
??

**Comment by cattivik39** [comment]
sorry the problem is solved when installing latest version of kk
