### ISSUE TITLE
官方文档环境要求中未声明KubeSphere 3.3.2 版本对 Kubernetes 版本支持的情况

### ISSUE THREAD

**Issue by hxrui** [kubesphere/website#2858]
描述：环境要求中未声明KubeSphere 3.3.2 版本对 Kubernetes 版本支持的情况。
链接：https://kubesphere.io/zh/docs/v3.3/reference/environment-requirements/#%E6%94%AF%E6%8C%81%E7%9A%84-kubernetes-%E7%89%88%E6%9C%AC
希望补充描述下，谢谢~

**Comment by faweizhao26** [comment]
Thanks, we will add it.
