### ISSUE TITLE
Website announcement  version 3.3.2 wrong release notes link

### ISSUE THREAD

**Issue by mistadave** [kubesphere/website#2875]
The announcement link on the Main [website](https://kubesphere.io)  about the new version 3.3.2 release notes has a wrong link to version 3.3.1. 
![image](https://user-images.githubusercontent.com/7965357/231457753-46ea7f4a-6614-4e50-97de-a924a75c7660.png)

**Comment by faweizhao26** [comment]
Thanks for your information. We have update the header. So I close this issue now.
