### ISSUE TITLE
KubeSphere 中文文档（持久化声明）章节中“备注”有重复的解释

### ISSUE THREAD

**Issue by Dragon-zw** [kubesphere/website#2931]
在 KubeSphere 中文文档官网（持久卷声明）：https://www.kubesphere.io/zh/docs/v3.3/project-user-guide/storage/volumes/

文档中的“创建持久性声明“章节中的“备注”有重复的解释。

**Comment by faweizhao26** [comment]
Thans for your information. I will fix it today.

**Comment by Dragon-zw** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
