### ISSUE TITLE
Text overlaps in the page

### ISSUE THREAD

**Issue by PranitRout07** [kubesphere/website#3000]
**ISSUE DETAILS**
The issue is related to UI. This happens when you scroll down the page.  As far i have seen it is the problem in most of the pages .

 **FOLLOW THESE STEPS TO SEE THE ISSUE**

->Go to this link https://kubesphere.io/docs/v3.4/
->Just slightly scroll down and look at the top of the page.

**WHY TO SOLVE THIS ISSUE?**
To make the documentation pages look more good and clean.

**ISSUE SCREENSHOTS**
<img width="1280" alt="Screenshot 2023-10-17 164141" src="https://github.com/kubesphere/website/assets/102309095/807b6ae7-05d2-4e0c-9d97-368f0cc8323a">
<img width="1280" alt="Screenshot 2023-10-17 164200" src="https://github.com/kubesphere/website/assets/102309095/f1cab2fe-46ef-45c7-8a7f-b922023e3b70">

**Comment by faweizhao26** [comment]
What's your browser? I'm not reproducing the problem with Google Chrome.

**Comment by PranitRout07** [comment]
@faweizhao26 i am also using google chrome. I think you should slightly scroll down and look at the top of the page. Look at this short video and see my cursor :

https://github.com/kubesphere/website/assets/102309095/cb419560-b6a1-4a33-8822-00c43ea410ea
