### ISSUE TITLE
Feat: archive 2.x doc and leave a redirect info page to specific github link

### ISSUE THREAD

**Issue by calvinyv** [kubesphere/website#3114]
<img width="754" alt="iShot_2024-05-17_14 22 44" src="https://github.com/kubesphere/website/assets/28883416/af1989cc-ba91-4e44-bd23-1f341003231a">

**Comment by stoneshi-yunify** [comment]
建议：
- 只保留最近两个minor release 的文档。本例中，即 3.4 3.3.
- documentation 箭头下方，展示两个 minor release。两个minor release 下面，显示 `earlier releases`。点击earlier releases，进入一个页面，显示所有的earlier release 以及相应的文档链接。在此页面中，应突出显示（警告），下方所有的release 都已经不再维护，最新的release文档的链接是xxx。

cc @calvinyv @zheng1

**Comment by zheng1** [comment]
done
