### ISSUE TITLE
KubeSphere 4.1 文档的页面显示问题

### ISSUE THREAD

**Issue by zhuxiujuan28** [kubesphere/website#3167]
记录在 https://doc.weixin.qq.com/doc/w3_AY0AqQaQABw9Lq1LUUnQ12FM36QsB?scode=AM4AzgcZACcfNa1A04AY0AqQaQABw
重点需要处理后面2 个问题

**Comment by donniean** [comment]
以下提示框没有背景色。说明的背景色应该是蓝色，注意的背景色应该是黄色。

![image](https://github.com/user-attachments/assets/f9f6a711-15ad-4a16-8154-a2bdc6f2f5e2)

![image](https://github.com/user-attachments/assets/78c79093-dd17-4b64-9491-58b9e8fd2d61)

![image](https://github.com/user-attachments/assets/de31f94b-4147-45fd-9cde-86971c5a064f)

**Comment by donniean** [comment]
上一篇、下一篇，展示不对

![image](https://github.com/user-attachments/assets/0f864b03-abfc-4b4c-b0b8-3323ee6ac6d9)

文档中的 weight 值需要设置好，需要整体做好规划，会根据这整个站点中的 weight 来排序显示上一页下一页。

**Comment by donniean** [comment]
上方目录显示错误。hover 在“文档”旁的图标时，出现以下错误

![image](https://github.com/user-attachments/assets/0e570f49-b1d7-43b4-a603-87da2a936675)
