### ISSUE TITLE
Air-gapped installation and upgrade

### ISSUE THREAD

**Issue by FeynmanZhou** [kubesphere/website#359]
We are going to test and prepare for these guides:

- [ ] Air-gapped installation on existing Kubernetes
- [ ] Air-gapped Upgrades (Multi-node)

**Comment by ruiyaoOps** [comment]
Air-gapped Upgrades (Multi-node), yeah, i will try this.

**Comment by misteruly** [comment]
Air-gapped installation on existing Kubernetes，I choose this one

**Comment by FeynmanZhou** [comment]
> Air-gapped installation on existing Kubernetes，I choose this one

Cool, you can reference these guides to getting started with v3.0.0:

https://v2-1.docs.kubesphere.io/docs/installation/install-on-k8s-airgapped/
https://kubesphere.com.cn/forum/d/2034-kubekey-kubesphere-v3-0-0

**Comment by ruiyaoOps** [comment]
Air-gapped Upgrades (Multi-node) I have pr. Please review  https://github.com/kubesphere/website/pull/378 @FeynmanZhou

**Comment by misteruly** [comment]
https://github.com/kubesphere/website/pull/395  @FeynmanZhou

**Comment by misteruly** [comment]
Air-gapped installation on existing Kubernetes .this is my PR.Please review   https://github.com/kubesphere/website/pull/395@FeynmanZhou

**Comment by misteruly** [comment]
Air-gapped installation on existing Kubernetes .this is my PR.Please review #395 @FeynmanZhou

**Comment by FeynmanZhou** [comment]
> Air-gapped installation on existing Kubernetes .this is my PR.Please review #395 @FeynmanZhou

Thanks, working on it.

**Comment by Sherlock113** [comment]
Air-gapped installation and upgrade guides are already available.
