### ISSUE TITLE
Localization task for KubeSphere on AWS quickstart

### ISSUE THREAD

**Issue by FeynmanZhou** [kubesphere/website#564]
- [x] Overview ~ Planning the deployment (Technical requirements) 
- [ ] Deployment steps ~ Additional resources
- [ ] FAQ ~ Notices

Ref: https://github.com/aws-quickstart/quickstart-qingcloud-kubesphere/issues/40

**Comment by Sherlock113** [comment]
I will translate the last part.

I forked the repository. This is my repository address: https://github.com/Sherlock113/quickstart-qingcloud-kubesphere. You guys can submit prs to the develop branch of my personal repository. After all the translation is done, I will submit the pr to the upstream branch. @FeynmanZhou @calvinyv

**Comment by FeynmanZhou** [comment]
Ok, I will choose these sections `Deployment steps ~ Additional resources`. 

The first part is the same as the landing page, @calvinyv , could you pick this part?

**Comment by calvinyv** [comment]
@FeynmanZhou @Sherlock113 I'm not very familiar with this document structure, so for a quick catch-up, could you tell me directly which files should I update? for example, which files under https://github.com/Sherlock113/quickstart-qingcloud-kubesphere/tree/main/docs/partner_editable?
