### ISSUE TITLE
v3.0.0 devops-user-guide same pages is return 404

### ISSUE THREAD

**Issue by LyonLee** [kubesphere/website#634]
https://v3-0.docs.kubesphere.io/zh/docs/devops-user-guide/how-to-use/devops-project-management/ is 404

**Comment by shaowenchen** [comment]
please visit https://v3-0.docs.kubesphere.io/docs/devops-user-guide/how-to-use/devops-project-management/. Chinese documents are being translated

**Comment by LyonLee** [comment]
ok thx~
