### ISSUE TITLE
The icon is missing on China site

### ISSUE THREAD

**Issue by FeynmanZhou** [kubesphere/website#873]
Access the [China site](https://kubesphere.com.cn/), you will find this bug.

![image](https://user-images.githubusercontent.com/40452856/103624226-36da2a00-4f74-11eb-8443-52ec2fc8f333.png)

**Comment by FeynmanZhou** [comment]
area/bug

**Comment by FeynmanZhou** [comment]
kind/bug

**Comment by liuboaibc** [comment]
The icon in my browser is normal

**Comment by FeynmanZhou** [comment]
> The icon in my browser is normal

Chrome? Can you share your screenshot?

**Comment by liuboaibc** [comment]
<img width="996" alt="WeChat7f9e9bfa98dd6d85fb2c0cb63307cd2e" src="https://user-images.githubusercontent.com/39849463/103723911-18c10800-500e-11eb-977c-0222a6ae2cb8.png">

**Comment by liuboaibc** [comment]
chrome
