### ISSUE TITLE
Upload videos to media channels

### ISSUE THREAD

**Issue by FeynmanZhou** [kubesphere/website#93]
## Upload these videos to bilibili.com:

Please refer to the [quick start guide](https://kubesphere.com.cn/docs/zh-CN/quick-start/admin-quick-start/) to give titles to the following videos.

![image](https://user-images.githubusercontent.com/40452856/86077262-3b51f180-babe-11ea-9598-e75331d47af8.png)

![image](https://user-images.githubusercontent.com/40452856/86077281-44db5980-babe-11ea-953d-161a15eaaaaa.png)

Please refer to the [Meetup post](https://kubesphere.com.cn/forum/d/472-kubesphere-meetup-ppt) to give titles to the following videos.

![image](https://user-images.githubusercontent.com/40452856/86078877-a81abb00-bac1-11ea-9311-0481d6baf0ca.png)

![image](https://user-images.githubusercontent.com/40452856/86077791-3d688000-babf-11ea-86cc-e419ea4a2937.png)

## Upload these videos to Youtube.

![image](https://user-images.githubusercontent.com/40452856/86077967-91736480-babf-11ea-932b-8d32e1cab9f9.png)

**Comment by FeynmanZhou** [comment]
Assign to @Sherlock113

**Comment by Sherlock113** [comment]
Apart from videos that already exist in Bilibili.com, other videos have all been uploaded to Bilibili.com and youtube respectively.
